apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: echo-nginx
  name: echo-nginx-configmap
  namespace: echo
data:
  default.conf: |-
    map $sent_http_content_type $expires {
      "text/html"                 epoch;
      "text/html; charset=utf-8"  epoch;
      default                     off;
    }

    upstream echo-app {
        server echo-app:8080;
    }

    server {
      listen 443 ssl;
      server_name example.com;
      server_tokens off;

      ssl_certificate /etc/nginx/certs/tls.crt;
      ssl_certificate_key /etc/nginx/certs/tls.key;

      location / {
            gzip_static                         on;
            expires                             $expires;
            proxy_pass                          http://echo-app;
            proxy_redirect                      off;
            proxy_set_header                    Host $host;
            proxy_set_header X-Real-IP          $remote_addr;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto  $scheme;
            proxy_read_timeout                  1m;
            proxy_connect_timeout               1m;
        }
    }