apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-selfsigned-cert
  namespace: echo
spec:
  secretName: echo-nginx-tls-certificate-certmanager
  issuerRef:
    name: selfsigner-issuer
    kind: ClusterIssuer
  commonName: advanced-network-security.com