apiVersion: v1
kind: Service
metadata:
  name: echo-nginx
  namespace: echo
spec:
  selector:
    app: echo-nginx 
  ports:
    - protocol: TCP
      port: 443    # Port inside the Kubernetes cluster
      targetPort: 443  # Port exposed by the NGINX container
  type: NodePort  

---
apiVersion: v1
kind: Service
metadata:
  name: echo-app 
  namespace: echo
spec:
  selector:
    app: echo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
