apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-nginx
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-nginx
  template:
    metadata:
      labels:
        app: echo-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: echo-tls-certs
              mountPath: /etc/nginx/certs
              readOnly: true
            - name: echo-config
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
              subPath: default.conf
      volumes:
        - name: echo-tls-certs
          secret:
            secretName: echo-nginx-tls-certificate-certmanager
        - name: echo-config
          configMap:
            name: echo-nginx-configmap
