apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
        - name: echo-app
          image: kicbase/echo-server:latest
          ports:
            - containerPort: 8080
