apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: sax
spec:
  selector:
    app: nginx-server  # Match the labels used in the Deployment
  ports:
    - protocol: TCP
      port: 80    # Port inside the Kubernetes cluster
      targetPort: 80  # Port exposed by the NGINX container
  type: NodePort  